models:
  Claude 3 Sonnet:
    model_id: "anthropic.claude-3-sonnet-20240229-v1:0"
    input_format: "list_of_dicts"
    temperature: 1.0
    top_p: 1.0
    top_k: 500
    max_tokens: 4096
    memory_window: 10
    max_top_k: 500
  Claude 3 Haiku:
    model_id: "anthropic.claude-3-haiku-20240307-v1:0"
    input_format: "list_of_dicts"
    temperature: 1.0
    top_p: 1.0
    top_k: 500
    max_tokens: 4096
    memory_window: 10
    max_top_k: 500
  Mistral Large:
    model_id: "mistral.mistral-large-2402-v1:0"
    input_format: "text"
    system_prompt_disabled: true
    temperature: 1.0
    top_p: 1.0
    top_k: 200
    max_tokens: 4096
    memory_window: 10
    max_top_k: 200
    image_upload_disabled: true
